#!/bin/bash
# Find high memory usage ArchiveBot jobs
{ echo "PID RSS JOBID"; ps -C wpull --format 'pid,rss,cmd' --no-headers | sed 's,^\s*,,; s,^\([0-9]\+ [0-9]\+ \).*/data/[^/]\+/\([0-9a-z]\+\)/wpull\.log.*$,\1\2,'; } | column -t
