#!/bin/bash
hashtag="$1"
shift
{
	echo "https://twitter.com/hashtag/${hashtag}"
	echo "https://twitter.com/hashtag/${hashtag}?src=hash"
	echo "https://twitter.com/hashtag/${hashtag}?f=tweets&vertical=default"
	echo "https://twitter.com/hashtag/${hashtag}?f=tweets&vertical=default&src=hash"
	snscrape "$@" twitter-hashtag "${hashtag}"
} > "twitter-#${hashtag}"
