#!/bin/bash
hashtag="$1"
shift
{
	echo "https://twitter.com/hashtag/${hashtag}"
	echo "https://twitter.com/hashtag/${hashtag}?src=hash"
	echo "https://twitter.com/hashtag/${hashtag}?f=tweets&vertical=default"
	echo "https://twitter.com/hashtag/${hashtag}?f=tweets&vertical=default&src=hash"
	snscrape --format '{url} {tcooutlinksss} {outlinksss}' "$@" twitter-hashtag "${hashtag}" | tr ' ' '\n' | grep -v '^$' | awk '!seen[$0]++'
} > "twitter-#${hashtag}"
