#!/bin/bash
origUser="$1"
shift
user="$(snscrape --max-results 1 twitter-user "${origUser}" | grep -Po '^https?://twitter\.com/\K[^/]+')"
if [[ "${user}" ]]
then
	if [[ "${user}" != "${origUser}" ]]; then echo "Username fix: ${origUser} -> ${user}" >&2; fi
	{
		echo "https://twitter.com/${user}"
		snscrape --format '{url} {tcooutlinksss} {outlinksss}' "$@" twitter-user "${user}"
	} | tr ' ' '\n' | grep -v '^$' | awk '!seen[$0]++' > "twitter-@${user}"
fi
