#!/bin/bash
while read -r url
do
	if [[ "${url}" == '* '* ]]
	then
		prefix='* '
		url="${url:2}"
	else
		prefix=''
	fi

	if [[ "${url}" =~ ^https?://(www\.)?youtube\.com/ ]]
	then
		if [[ "${url}" == *'?'* ]]
		then
			rurl="${url}&disable_polymer=1"
		else
			rurl="${url}?disable_polymer=1"
		fi
		page="$(curl -4sL -A 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36' -H 'Accept-Language: en-US,en;q=0.5' "${rurl}")"
		canonical="$(grep -Po '<link itemprop="url" href="http://www\.youtube\.com/\Kuser/[^"]+' <<< "${page}")"
		if [[ "${canonical}" ]]
		then
			echo "${prefix}https://www.youtube.com/${canonical}"
		else
			canonical="$(grep -Po '<link itemprop="url" href="http://www\.youtube\.com/\Kchannel/[^"]+' <<< "${page}")"
			if [[ "${canonical}" ]]
			then
				echo "${prefix}https://www.youtube.com/${canonical}"
			else
				echo "${prefix}${url}"
			fi
		fi
	else
		echo "${prefix}${url}"
	fi
done
